### ISSUE TITLE
Prueba

### ISSUE THREAD

**Issue by jossoj** [jossoj/OCP.7.JaVa#1]
Prueba

**Comment by jossoj** [comment]
Anda como un jira 

Lo sincronice pero es algo raro.. hice dos proyecto, uno se subio bien, y el otro no... el otro se quedo mal y lo puso todo en raiz..

Estoy haciendolo sobre el brack Version 1.0

johann si puedes miralo please

Saludos

**Comment by jossoj** [comment]
Parece que ya lo voy pillando, lo he sincronizado ya con Eclipse y también con mi carpeta, por si hay que mover/eliminar cosas....

Lo doy por cerrado.

Gracias.

**Comment by johannpando** [comment]
Gracias Chema, a ver si me puedo poner con ello hoy.
